server:
  port: 8089  # Puerto de la aplicación
spring:
  application:
    name: PRODUCT-MICROSERVICE

  datasource:
    url: jdbc:postgresql://ep-misty-credit-a59y8o5v-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_PvN8fn4lMrZC
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update  # Changed from create to update for production
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL dialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.products.product: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true


# Cloudinary Configuration
cloudinary:
  cloud_name: djyuwhvh9
  api_key: 836385768495892
  api_secret: Pj62xMu8EfXVHGuTkXcHAW-iuOo

