server:
  port: 8088  # Puerto de la aplicación
spring:
    application:
        name: product
    datasource:
        url: 
        username: 
        password: 
        driver-class-name: org.postgresql.Driver  # PostgreSQL driver

    jpa:
        hibernate:
            ddl-auto: update  # Changed from create to update for production
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL dialect

    eureka:
        client:
            serviceUrl:
                defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        instance:
            preferIpAddress: true

# Cloudinary Configuration
cloudinary:
    cloud_name: djyuwhvh9
    api_key: 836385768495892
    api_secret: Pj62xMu8EfXVHGuTkXcHAW-iuOo