apiVersion: v1
kind: Service
metadata:
  name: microservice-producto
spec:
  selector:
    app: microservice-producto
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP